### PR TITLE
undo directive extension workaround for angular1.2

### LINKED ISSUE #3: $$isolateBindings
The following line doesn't work in Angular 1.2.29:

```
// dist/ui-leaflet-draw.js, line 47
directive.$$isolateBindings[directiveName]
```

http://plnkr.co/edit/8kvQw2LZTYDa2AjAwjnc?p=info
Check dev console to see that `$$isolateBindings` doesn't exist.

### PR DESCRIPTION
**Pull request by anilanar**
Fixes #3.

### CODE REVIEW

File: src/drawDirective.coffee [hunk 1]
```diff
@@ -4,10 +4,9 @@ angular.module('ui-leaflet')
   #Extend root leaflet directive
   $provide.decorator 'leafletDirective', ($delegate) ->
     directive = $delegate[0]
-    #directive.scope[directiveName] = '=?' #the way it should be
-    #the above should derrive $$isolateBindings this without the below hack
-    #workaround from http://plnkr.co/edit/CRxhX6?p=preview
-    directive.$$isolateBindings[directiveName] =
+    directive.scope[directiveName] = '=?' #angular1.2.x
+    #angular^1.3, https://github.com/angular/angular.js/issues/10149
+    directive.$$isolateBindings?[directiveName] =
```
Comment (nmccready) [inline src/drawDirective.coffee]: note this is gone in angular 1.4.10
